version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - marketplace
      - web_server

  db:
    image: mysql:8.0
    container_name: marketplace-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - marketplace
    ports:
      - "3306:3306"

networks:
  marketplace:
    driver: bridge
  web_server:
    driver: bridge
    external: true

volumes:
  dbdata:
    driver: local
